# Generated by Django 5.1.2 on 2024-11-17 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderitem_user_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Payment_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30, null=True)),
                ('card_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=200)),
                ('cvc', models.CharField(max_length=3)),
                ('expires_at', models.DateField()),
                ('user_session', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
