# Generated by Django 5.1 on 2024-10-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_remove_cart_total_price_alter_orderitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pedido',
            new_name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
