# Generated by Django 5.1.2 on 2024-11-17 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_payment_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_payment_card',
            name='method',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User_Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('complement', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
