# Generated by Django 5.1.1 on 2024-10-01 23:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pedido_payment_order_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=0, upload_to=app.models.get_file_path),
            preserve_default=False,
        ),
    ]
