# Generated by Django 5.1.2 on 2024-11-26 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_id_user_adress_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user_adress',
            constraint=models.UniqueConstraint(fields=('street', 'number', 'complement', 'district', 'state', 'city'), name='unique_address_constraint'),
        ),
    ]
