# Generated by Django 5.1.2 on 2024-11-27 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_adress_unique_address_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
